###############################################################################
# IO-107 SDLC Pipeline -- lab_env_student / variables.tf
#
# Generated by labforge untagged on 2026-05-25.
###############################################################################

variable "aws_region" {
  description = "AWS region for the whole lab environment."
  type        = string
  default     = "us-east-1"
}

variable "student_id" {
  description = "Short identifier for the student running these labs (e.g. alice, ltf-smoketest). Used as a uniqueness suffix on every per-student resource. Must be lowercase, 1-16 chars, [a-z0-9-]."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9-]{1,16}$", var.student_id))
    error_message = "student_id must be lowercase letters, digits, or dashes, 1-16 characters."
  }
}

variable "vpc_cidr" {
  description = "CIDR for the lab VPC. Pick something that doesn't overlap with anything else in the account."
  type        = string
  default     = "10.20.0.0/16"
}

variable "eks_kubernetes_version" {
  description = "Kubernetes version for the EKS cluster."
  type        = string
  default     = "1.29"
}

variable "eks_node_instance_types" {
  description = "Instance types for the EKS managed node group."
  type        = list(string)
  default     = ["t3.medium"]
}

variable "eks_node_desired_size" {
  description = "Desired worker node count."
  type        = number
  default     = 2
}


variable "enable_lab1" {
  description = "Provision per-lab resources for lab1."
  type        = bool
  default     = true
}

variable "enable_lab2" {
  description = "Provision per-lab resources for lab2."
  type        = bool
  default     = true
}

variable "enable_lab3" {
  description = "Provision per-lab resources for lab3."
  type        = bool
  default     = true
}

variable "enable_lab4" {
  description = "Provision per-lab resources for lab4."
  type        = bool
  default     = true
}


# Note: in student mode the CodePipeline Source action reads from each lab's
# per-student CodeCommit repo (seeded once from the public monorepo at apply
# time). No GitHub CodeStar connection is needed -- the seed clone is from a
# public repo and the runtime source is CodeCommit. Split mode (multi-student
# delivery) is the path that still needs a CodeStar GitHub connection.
