###############################################################################
# IO-107 SDLC Pipeline — student_bootstrap / main.tf
#
# Per-student-per-lab provisioning. Run this ONCE per student before any lab.
#
# What this module creates per student:
#   lab1:
#     - CodePipeline (lab1-${var.student_id})
#     - CodeBuild project
#     - S3 artifact bucket (globally-unique name with student_id suffix)
#     - IRSA role(s): myapp-dev-role, myapp-stg-role


#   lab2:
#     - CodePipeline (lab2-${var.student_id})
#     - CodeBuild project
#     - S3 artifact bucket (globally-unique name with student_id suffix)



#   lab3:
#     - CodePipeline (lab3-${var.student_id})
#     - CodeBuild project
#     - S3 artifact bucket (globally-unique name with student_id suffix)



#   lab4:
#     - CodePipeline (lab4-${var.student_id})
#     - CodeBuild project
#     - S3 artifact bucket (globally-unique name with student_id suffix)


#     - Aurora cluster: training-aurora-${var.student_id} (Blue/Green can't share clusters)
#
# What this module DOES NOT create:
#   - Anything in the INSTRUCTOR_SHARED_PER_REGION bucket (see training_env/)
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

locals {
  common_tags = {
    Course      = "IO-107 SDLC Pipeline"
    Environment = "training"
    ManagedBy   = "labforge"
    StudentId   = var.student_id
  }
}

# ----- Read shared state from training_env ---------------------------------

data "terraform_remote_state" "training_env" {
  backend = var.training_env_backend_type
  config  = var.training_env_remote_state
}

# ----- Per-lab modules ------------------------------------------------------

# ============================================================================
# LAB1 — Lab 1: End-to-End EKS Deployment Pipeline
# Fixture repo: https://github.com/jessetop/io107-lab1-eks-app
# ============================================================================

resource "aws_s3_bucket" "lab1_artifacts" {
  count = var.enable_lab1 ? 1 : 0

  bucket        = "io107-lab1-${var.student_id}-artifacts"
  force_destroy = true
  tags          = merge(local.common_tags, { Lab = "lab1" })
}

resource "aws_s3_bucket_versioning" "lab1_artifacts" {
  count  = var.enable_lab1 ? 1 : 0
  bucket = aws_s3_bucket.lab1_artifacts[0].id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "lab1_artifacts" {
  count  = var.enable_lab1 ? 1 : 0
  bucket = aws_s3_bucket.lab1_artifacts[0].id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = data.terraform_remote_state.training_env.outputs.kms_s3_key_arn
    }
  }
}

resource "aws_codebuild_project" "lab1" {
  count = var.enable_lab1 ? 1 : 0

  name         = "io107-lab1-${var.student_id}-build"
  description  = "IO-107 SDLC Pipeline lab1 per-student CodeBuild project"
  service_role = data.terraform_remote_state.training_env.outputs.codebuild_service_role_arn

  artifacts { type = "CODEPIPELINE" }

  environment {
    compute_type    = "BUILD_GENERAL1_SMALL"
    image           = "aws/codebuild/standard:7.0"
    type            = "LINUX_CONTAINER"
    privileged_mode = true   # required for docker build (Lab 1) — harmless for others

    environment_variable {
      name  = "AWS_DEFAULT_REGION"
      value = var.aws_region
    }
    environment_variable {
      name  = "STUDENT_ID"
      value = var.student_id
    }
    environment_variable {
      name  = "CLUSTER_NAME"
      value = data.terraform_remote_state.training_env.outputs.eks_cluster_name
    }
    environment_variable {
      name  = "NAMESPACE"
      value = "-${var.student_id}"
    }
    environment_variable {
      name  = "APP_NAME"
      value = "myapp"
    }
    environment_variable {
      name  = "ECR_REGISTRY"
      value = split("/", data.terraform_remote_state.training_env.outputs.ecr_repo_urls["myapp"])[0]
    }
    environment_variable {
      name  = "ENVIRONMENT"
      value = "dev"
    }
  }

  source {
    type      = "CODEPIPELINE"
    buildspec = "buildspec.yml"
  }

  logs_config {
    cloudwatch_logs {
      group_name  = "/aws/codebuild/io107-lab1-${var.student_id}"
      stream_name = "build"
    }
  }

  tags = merge(local.common_tags, { Lab = "lab1" })
}

resource "aws_codepipeline" "lab1" {
  count = var.enable_lab1 ? 1 : 0

  name     = "io107-lab1-${var.student_id}"
  role_arn = data.terraform_remote_state.training_env.outputs.codepipeline_service_role_arn

  artifact_store {
    location = aws_s3_bucket.lab1_artifacts[0].bucket
    type     = "S3"
  }

  stage {
    name = "Source"
    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source_output"]

      configuration = {
        ConnectionArn    = data.terraform_remote_state.training_env.outputs.codestar_connection_arn
        FullRepositoryId = "jessetop/io107-lab1-eks-app"
        BranchName       = "main"
      }
    }
  }

  stage {
    name = "Build"
    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      version          = "1"
      input_artifacts  = ["source_output"]
      output_artifacts = ["build_output"]

      configuration = {
        ProjectName = aws_codebuild_project.lab1[0].name
      }
    }
  }

  tags = merge(local.common_tags, { Lab = "lab1" })
}




resource "aws_iam_role" "lab1_myapp_dev_role" {
  count = var.enable_lab1 ? 1 : 0

  name = "myapp-dev-role-${var.student_id}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Federated = data.terraform_remote_state.training_env.outputs.eks_oidc_provider_arn
      }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringEquals = {
          "${replace(data.terraform_remote_state.training_env.outputs.eks_oidc_issuer, "https://", "")}:sub" = "system:serviceaccount:-${var.student_id}:myapp-sa"
          "${replace(data.terraform_remote_state.training_env.outputs.eks_oidc_issuer, "https://", "")}:aud" = "sts.amazonaws.com"
        }
      }
    }]
  })

  tags = merge(local.common_tags, { Lab = "lab1", IrsaRole = "myapp-dev-role" })
}

# Minimal lab-purpose policy. Tighten per workload before promoting any pattern
# from this lab to production. Today's grant: read shared training KMS, list
# the training data bucket, write logs.
resource "aws_iam_role_policy" "lab1_myapp_dev_role" {
  count = var.enable_lab1 ? 1 : 0
  name  = "myapp-dev-role-${var.student_id}-inline"
  role  = aws_iam_role.lab1_myapp_dev_role[0].id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["s3:ListBucket", "s3:GetObject"]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = ["kms:Decrypt", "kms:GenerateDataKey"]
        Resource = [
          data.terraform_remote_state.training_env.outputs.kms_s3_key_arn,
          data.terraform_remote_state.training_env.outputs.kms_logs_key_arn
        ]
      },
      {
        Effect   = "Allow"
        Action   = ["logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_role" "lab1_myapp_stg_role" {
  count = var.enable_lab1 ? 1 : 0

  name = "myapp-stg-role-${var.student_id}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Federated = data.terraform_remote_state.training_env.outputs.eks_oidc_provider_arn
      }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringEquals = {
          "${replace(data.terraform_remote_state.training_env.outputs.eks_oidc_issuer, "https://", "")}:sub" = "system:serviceaccount:-${var.student_id}:myapp-sa"
          "${replace(data.terraform_remote_state.training_env.outputs.eks_oidc_issuer, "https://", "")}:aud" = "sts.amazonaws.com"
        }
      }
    }]
  })

  tags = merge(local.common_tags, { Lab = "lab1", IrsaRole = "myapp-stg-role" })
}

# Minimal lab-purpose policy. Tighten per workload before promoting any pattern
# from this lab to production. Today's grant: read shared training KMS, list
# the training data bucket, write logs.
resource "aws_iam_role_policy" "lab1_myapp_stg_role" {
  count = var.enable_lab1 ? 1 : 0
  name  = "myapp-stg-role-${var.student_id}-inline"
  role  = aws_iam_role.lab1_myapp_stg_role[0].id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["s3:ListBucket", "s3:GetObject"]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = ["kms:Decrypt", "kms:GenerateDataKey"]
        Resource = [
          data.terraform_remote_state.training_env.outputs.kms_s3_key_arn,
          data.terraform_remote_state.training_env.outputs.kms_logs_key_arn
        ]
      },
      {
        Effect   = "Allow"
        Action   = ["logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = "*"
      }
    ]
  })
}




# ============================================================================
# LAB2 — Lab 2: Lambda Deployment with SAM
# Fixture repo: https://github.com/jessetop/io107-lab2-sam-app
# ============================================================================

resource "aws_s3_bucket" "lab2_artifacts" {
  count = var.enable_lab2 ? 1 : 0

  bucket        = "io107-lab2-${var.student_id}-artifacts"
  force_destroy = true
  tags          = merge(local.common_tags, { Lab = "lab2" })
}

resource "aws_s3_bucket_versioning" "lab2_artifacts" {
  count  = var.enable_lab2 ? 1 : 0
  bucket = aws_s3_bucket.lab2_artifacts[0].id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "lab2_artifacts" {
  count  = var.enable_lab2 ? 1 : 0
  bucket = aws_s3_bucket.lab2_artifacts[0].id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = data.terraform_remote_state.training_env.outputs.kms_s3_key_arn
    }
  }
}

resource "aws_codebuild_project" "lab2" {
  count = var.enable_lab2 ? 1 : 0

  name         = "io107-lab2-${var.student_id}-build"
  description  = "IO-107 SDLC Pipeline lab2 per-student CodeBuild project"
  service_role = data.terraform_remote_state.training_env.outputs.codebuild_service_role_arn

  artifacts { type = "CODEPIPELINE" }

  environment {
    compute_type    = "BUILD_GENERAL1_SMALL"
    image           = "aws/codebuild/standard:7.0"
    type            = "LINUX_CONTAINER"
    privileged_mode = true   # required for docker build (Lab 1) — harmless for others

    environment_variable {
      name  = "AWS_DEFAULT_REGION"
      value = var.aws_region
    }
    environment_variable {
      name  = "STUDENT_ID"
      value = var.student_id
    }
  }

  source {
    type      = "CODEPIPELINE"
    buildspec = "buildspec.yml"
  }

  logs_config {
    cloudwatch_logs {
      group_name  = "/aws/codebuild/io107-lab2-${var.student_id}"
      stream_name = "build"
    }
  }

  tags = merge(local.common_tags, { Lab = "lab2" })
}

resource "aws_codepipeline" "lab2" {
  count = var.enable_lab2 ? 1 : 0

  name     = "io107-lab2-${var.student_id}"
  role_arn = data.terraform_remote_state.training_env.outputs.codepipeline_service_role_arn

  artifact_store {
    location = aws_s3_bucket.lab2_artifacts[0].bucket
    type     = "S3"
  }

  stage {
    name = "Source"
    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source_output"]

      configuration = {
        ConnectionArn    = data.terraform_remote_state.training_env.outputs.codestar_connection_arn
        FullRepositoryId = "jessetop/io107-lab2-sam-app"
        BranchName       = "main"
      }
    }
  }

  stage {
    name = "Build"
    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      version          = "1"
      input_artifacts  = ["source_output"]
      output_artifacts = ["build_output"]

      configuration = {
        ProjectName = aws_codebuild_project.lab2[0].name
      }
    }
  }

  tags = merge(local.common_tags, { Lab = "lab2" })
}







# ============================================================================
# LAB3 — Lab 3: Policy-as-Code Evaluation & Failure Remediation
# Fixture repo: https://github.com/jessetop/io107-lab3-policy-violations
# ============================================================================

resource "aws_s3_bucket" "lab3_artifacts" {
  count = var.enable_lab3 ? 1 : 0

  bucket        = "io107-lab3-${var.student_id}-artifacts"
  force_destroy = true
  tags          = merge(local.common_tags, { Lab = "lab3" })
}

resource "aws_s3_bucket_versioning" "lab3_artifacts" {
  count  = var.enable_lab3 ? 1 : 0
  bucket = aws_s3_bucket.lab3_artifacts[0].id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "lab3_artifacts" {
  count  = var.enable_lab3 ? 1 : 0
  bucket = aws_s3_bucket.lab3_artifacts[0].id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = data.terraform_remote_state.training_env.outputs.kms_s3_key_arn
    }
  }
}

resource "aws_codebuild_project" "lab3" {
  count = var.enable_lab3 ? 1 : 0

  name         = "io107-lab3-${var.student_id}-build"
  description  = "IO-107 SDLC Pipeline lab3 per-student CodeBuild project"
  service_role = data.terraform_remote_state.training_env.outputs.codebuild_service_role_arn

  artifacts { type = "CODEPIPELINE" }

  environment {
    compute_type    = "BUILD_GENERAL1_SMALL"
    image           = "aws/codebuild/standard:7.0"
    type            = "LINUX_CONTAINER"
    privileged_mode = true   # required for docker build (Lab 1) — harmless for others

    environment_variable {
      name  = "AWS_DEFAULT_REGION"
      value = var.aws_region
    }
    environment_variable {
      name  = "STUDENT_ID"
      value = var.student_id
    }
  }

  source {
    type      = "CODEPIPELINE"
    buildspec = "buildspec.yml"
  }

  logs_config {
    cloudwatch_logs {
      group_name  = "/aws/codebuild/io107-lab3-${var.student_id}"
      stream_name = "build"
    }
  }

  tags = merge(local.common_tags, { Lab = "lab3" })
}

resource "aws_codepipeline" "lab3" {
  count = var.enable_lab3 ? 1 : 0

  name     = "io107-lab3-${var.student_id}"
  role_arn = data.terraform_remote_state.training_env.outputs.codepipeline_service_role_arn

  artifact_store {
    location = aws_s3_bucket.lab3_artifacts[0].bucket
    type     = "S3"
  }

  stage {
    name = "Source"
    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source_output"]

      configuration = {
        ConnectionArn    = data.terraform_remote_state.training_env.outputs.codestar_connection_arn
        FullRepositoryId = "jessetop/io107-lab3-policy-violations"
        BranchName       = "main"
      }
    }
  }

  stage {
    name = "Build"
    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      version          = "1"
      input_artifacts  = ["source_output"]
      output_artifacts = ["build_output"]

      configuration = {
        ProjectName = aws_codebuild_project.lab3[0].name
      }
    }
  }

  tags = merge(local.common_tags, { Lab = "lab3" })
}







# ============================================================================
# LAB4 — Lab 4: Aurora Blue/Green Deployment via Terraform + Pipeline
# Fixture repo: https://github.com/jessetop/io107-lab4-aurora-bluegreen
# ============================================================================

resource "aws_s3_bucket" "lab4_artifacts" {
  count = var.enable_lab4 ? 1 : 0

  bucket        = "io107-lab4-${var.student_id}-artifacts"
  force_destroy = true
  tags          = merge(local.common_tags, { Lab = "lab4" })
}

resource "aws_s3_bucket_versioning" "lab4_artifacts" {
  count  = var.enable_lab4 ? 1 : 0
  bucket = aws_s3_bucket.lab4_artifacts[0].id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "lab4_artifacts" {
  count  = var.enable_lab4 ? 1 : 0
  bucket = aws_s3_bucket.lab4_artifacts[0].id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = data.terraform_remote_state.training_env.outputs.kms_s3_key_arn
    }
  }
}

resource "aws_codebuild_project" "lab4" {
  count = var.enable_lab4 ? 1 : 0

  name         = "io107-lab4-${var.student_id}-build"
  description  = "IO-107 SDLC Pipeline lab4 per-student CodeBuild project"
  service_role = data.terraform_remote_state.training_env.outputs.codebuild_service_role_arn

  artifacts { type = "CODEPIPELINE" }

  environment {
    compute_type    = "BUILD_GENERAL1_SMALL"
    image           = "aws/codebuild/standard:7.0"
    type            = "LINUX_CONTAINER"
    privileged_mode = true   # required for docker build (Lab 1) — harmless for others

    environment_variable {
      name  = "AWS_DEFAULT_REGION"
      value = var.aws_region
    }
    environment_variable {
      name  = "STUDENT_ID"
      value = var.student_id
    }
    environment_variable {
      name  = "CLUSTER_ID"
      value = "training-aurora-${var.student_id}"
    }
  }

  source {
    type      = "CODEPIPELINE"
    buildspec = "buildspec.yml"
  }

  logs_config {
    cloudwatch_logs {
      group_name  = "/aws/codebuild/io107-lab4-${var.student_id}"
      stream_name = "build"
    }
  }

  tags = merge(local.common_tags, { Lab = "lab4" })
}

resource "aws_codepipeline" "lab4" {
  count = var.enable_lab4 ? 1 : 0

  name     = "io107-lab4-${var.student_id}"
  role_arn = data.terraform_remote_state.training_env.outputs.codepipeline_service_role_arn

  artifact_store {
    location = aws_s3_bucket.lab4_artifacts[0].bucket
    type     = "S3"
  }

  stage {
    name = "Source"
    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source_output"]

      configuration = {
        ConnectionArn    = data.terraform_remote_state.training_env.outputs.codestar_connection_arn
        FullRepositoryId = "jessetop/io107-lab4-aurora-bluegreen"
        BranchName       = "main"
      }
    }
  }

  stage {
    name = "Build"
    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      version          = "1"
      input_artifacts  = ["source_output"]
      output_artifacts = ["build_output"]

      configuration = {
        ProjectName = aws_codebuild_project.lab4[0].name
      }
    }
  }

  tags = merge(local.common_tags, { Lab = "lab4" })
}






resource "aws_rds_cluster" "lab4_aurora" {
  count = var.enable_lab4 ? 1 : 0

  cluster_identifier          = "training-aurora-${var.student_id}"
  engine                      = "aurora-postgresql"
  engine_version              = "15.4"
  database_name               = "training"
  master_username             = "training_admin"
  manage_master_user_password = true

  db_subnet_group_name   = data.terraform_remote_state.training_env.outputs.db_subnet_group_name
  vpc_security_group_ids = [data.terraform_remote_state.training_env.outputs.db_security_group_id]

  storage_encrypted = true
  kms_key_id        = data.terraform_remote_state.training_env.outputs.kms_rds_key_arn

  backup_retention_period             = 1   # minimum, this is a training cluster
  enabled_cloudwatch_logs_exports     = ["postgresql"]
  iam_database_authentication_enabled = true
  deletion_protection                 = false  # training cluster — allow tear-down

  skip_final_snapshot = true

  lifecycle {
    # Lab 4 flips engine_version via the CLI Blue/Green flow, not direct apply.
    ignore_changes = [engine_version]
  }

  tags = merge(local.common_tags, { Lab = "lab4" })
}

resource "aws_rds_cluster_instance" "lab4_aurora_writer" {
  count = var.enable_lab4 ? 1 : 0

  identifier         = "training-aurora-${var.student_id}-writer"
  cluster_identifier = aws_rds_cluster.lab4_aurora[0].id
  engine             = aws_rds_cluster.lab4_aurora[0].engine
  engine_version     = aws_rds_cluster.lab4_aurora[0].engine_version
  instance_class     = "db.t3.medium"

  tags = merge(local.common_tags, { Lab = "lab4" })
}


