###############################################################################
# IO-107 SDLC Pipeline — student_bootstrap / outputs.tf
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

output "lab1_pipeline_name" {
  value       = try(aws_codepipeline.lab1[0].name, "(not enabled)")
  description = "lab1 CodePipeline name for this student bootstrap."
}

output "lab1_artifact_bucket" {
  value       = try(aws_s3_bucket.lab1_artifacts[0].bucket, "(not enabled)")
  description = "lab1 pipeline artifact bucket for this student bootstrap."
}


output "lab2_pipeline_name" {
  value       = try(aws_codepipeline.lab2[0].name, "(not enabled)")
  description = "lab2 CodePipeline name for this student bootstrap."
}

output "lab2_artifact_bucket" {
  value       = try(aws_s3_bucket.lab2_artifacts[0].bucket, "(not enabled)")
  description = "lab2 pipeline artifact bucket for this student bootstrap."
}


output "lab3_pipeline_name" {
  value       = try(aws_codepipeline.lab3[0].name, "(not enabled)")
  description = "lab3 CodePipeline name for this student bootstrap."
}

output "lab3_artifact_bucket" {
  value       = try(aws_s3_bucket.lab3_artifacts[0].bucket, "(not enabled)")
  description = "lab3 pipeline artifact bucket for this student bootstrap."
}


output "lab4_pipeline_name" {
  value       = try(aws_codepipeline.lab4[0].name, "(not enabled)")
  description = "lab4 CodePipeline name for this student bootstrap."
}

output "lab4_artifact_bucket" {
  value       = try(aws_s3_bucket.lab4_artifacts[0].bucket, "(not enabled)")
  description = "lab4 pipeline artifact bucket for this student bootstrap."
}

output "lab4_aurora_endpoint" {
  value       = try(aws_rds_cluster.lab4_aurora[0].endpoint, "(not enabled)")
  description = "lab4 Aurora cluster endpoint for this student bootstrap."
}

