###############################################################################
# IO-107 SDLC Pipeline — student_bootstrap / variables.tf
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

variable "aws_region" {
  description = "Same region as the training_env apply."
  type        = string
  default     = "us-east-1"
}

variable "student_id" {
  description = "Short identifier for the student (e.g. alice, bob). Used as a prefix for all per-student resources. Must be lowercase, ≤16 chars, [a-z0-9-]."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9-]{1,16}$", var.student_id))
    error_message = "student_id must be lowercase letters, digits, or dashes, 1-16 characters."
  }
}

variable "training_env_remote_state" {
  description = "Backend config for the training_env state. Keys depend on backend type. Example for S3 backend: { bucket=\"...\", key=\"training_env/terraform.tfstate\", region=\"us-east-1\" }."
  type        = map(string)
}

variable "training_env_backend_type" {
  description = "Backend type used by training_env. Default: s3."
  type        = string
  default     = "s3"
}


variable "enable_lab1" {
  description = "Provision per-student resources for lab1."
  type        = bool
  default     = true
}

variable "enable_lab2" {
  description = "Provision per-student resources for lab2."
  type        = bool
  default     = true
}

variable "enable_lab3" {
  description = "Provision per-student resources for lab3."
  type        = bool
  default     = true
}

variable "enable_lab4" {
  description = "Provision per-student resources for lab4."
  type        = bool
  default     = true
}

