###############################################################################
# IO-107 SDLC Pipeline — student_bootstrap / versions.tf
#
# Per-student-per-lab provisioning. Each student runs this once before any lab.
# Uses terraform_remote_state to pull shared resources (EKS cluster, ECR,
# OIDC provider, security groups) from the training_env module's state.
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.40"
    }
  }
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      ManagedBy   = "labforge"
      Course      = "IO-107 SDLC Pipeline"
      Environment = "training"
      Module      = "student_bootstrap"
      StudentId   = var.student_id
    }
  }
}


