###############################################################################
# IO-107 SDLC Pipeline — training_env / main.tf
#
# Shared, instructor-owned, REGIONAL infrastructure for IO-107 SDLC Pipeline.
# One `terraform apply` per region. Creates everything in the
# INSTRUCTOR_SHARED_PER_REGION ownership bucket from the LabForge gap analysis.
#
# What this module creates:
#   - VPC, public + private subnets across 3 AZs, IGW, single NAT gateway
#   - EKS cluster (training-eks-cluster) + managed node group + IRSA OIDC provider
#   - DB subnet group + DB security group for the per-student Aurora clusters
#   - ECR repos for every containerised lab app
#   - KMS keys for storage, RDS, logs
#   - CodeStar source connection (one-time auth flow required after apply)
#   - CodeBuild service role used by all student pipelines
#   - Logging buckets (CloudTrail / pipeline access logs)
#
# What this module does NOT create:
#   - Student pipelines / CodeBuild projects — those are in student_bootstrap/
#   - The Aurora cluster itself — per-student, in student_bootstrap/ (Blue/Green can't be shared)
#   - SCPs / tag policies / AWS Config rules — apply at Org level separately
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

data "aws_availability_zones" "available" {
  state = "available"
}

locals {
  azs = slice(data.aws_availability_zones.available.names, 0, 3)

  common_tags = {
    Course      = "IO-107 SDLC Pipeline"
    Environment = "training"
    ManagedBy   = "labforge"
  }
}

# ----- VPC ------------------------------------------------------------------

resource "aws_vpc" "training" {
  cidr_block           = var.vpc_cidr
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags = merge(local.common_tags, {
    Name = "io107-training-vpc"
  })
}

resource "aws_subnet" "public" {
  count                   = 3
  vpc_id                  = aws_vpc.training.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 4, count.index)
  availability_zone       = local.azs[count.index]
  map_public_ip_on_launch = true

  tags = merge(local.common_tags, {
    Name                                            = "io107-public-${local.azs[count.index]}"
    "kubernetes.io/role/elb"                        = "1"
    "kubernetes.io/cluster/${var.eks_cluster_name}" = "shared"
  })
}

resource "aws_subnet" "private" {
  count             = 3
  vpc_id            = aws_vpc.training.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 4, count.index + 8)
  availability_zone = local.azs[count.index]

  tags = merge(local.common_tags, {
    Name                                            = "io107-private-${local.azs[count.index]}"
    "kubernetes.io/role/internal-elb"               = "1"
    "kubernetes.io/cluster/${var.eks_cluster_name}" = "shared"
  })
}

resource "aws_internet_gateway" "training" {
  vpc_id = aws_vpc.training.id
  tags   = merge(local.common_tags, { Name = "io107-igw" })
}

resource "aws_eip" "nat" {
  domain = "vpc"
  tags   = merge(local.common_tags, { Name = "io107-nat-eip" })
}

resource "aws_nat_gateway" "training" {
  subnet_id     = aws_subnet.public[0].id
  allocation_id = aws_eip.nat.id
  tags          = merge(local.common_tags, { Name = "io107-nat" })
}

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.training.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.training.id
  }

  tags = merge(local.common_tags, { Name = "io107-public-rt" })
}

resource "aws_route_table" "private" {
  vpc_id = aws_vpc.training.id

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.training.id
  }

  tags = merge(local.common_tags, { Name = "io107-private-rt" })
}

resource "aws_route_table_association" "public" {
  count          = 3
  subnet_id      = aws_subnet.public[count.index].id
  route_table_id = aws_route_table.public.id
}

resource "aws_route_table_association" "private" {
  count          = 3
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private.id
}

# ----- KMS ------------------------------------------------------------------

resource "aws_kms_key" "training_rds" {
  description             = "IO-107 SDLC Pipeline — Aurora / RDS storage encryption"
  deletion_window_in_days = 7
  enable_key_rotation     = true
  tags                    = local.common_tags
}

resource "aws_kms_alias" "training_rds" {
  name          = "alias/io107-training-rds"
  target_key_id = aws_kms_key.training_rds.key_id
}

resource "aws_kms_key" "training_logs" {
  description             = "IO-107 SDLC Pipeline — CloudWatch / CloudTrail log encryption"
  deletion_window_in_days = 7
  enable_key_rotation     = true
  tags                    = local.common_tags
}

resource "aws_kms_alias" "training_logs" {
  name          = "alias/io107-training-logs"
  target_key_id = aws_kms_key.training_logs.key_id
}

resource "aws_kms_key" "training_s3" {
  description             = "IO-107 SDLC Pipeline — S3 (artifact + data) encryption"
  deletion_window_in_days = 7
  enable_key_rotation     = true
  tags                    = local.common_tags
}

resource "aws_kms_alias" "training_s3" {
  name          = "alias/io107-training-s3"
  target_key_id = aws_kms_key.training_s3.key_id
}

# ----- ECR ------------------------------------------------------------------

resource "aws_ecr_repository" "app" {
  for_each = toset(var.ecr_repo_names)

  name                 = each.value
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  encryption_configuration {
    encryption_type = "KMS"
    kms_key         = aws_kms_key.training_s3.arn
  }

  tags = merge(local.common_tags, { App = each.value })
}

resource "aws_ecr_lifecycle_policy" "app" {
  for_each   = aws_ecr_repository.app
  repository = each.value.name

  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Keep only the most recent 50 images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 50
      }
      action = { type = "expire" }
    }]
  })
}

# ----- Security groups ------------------------------------------------------

resource "aws_security_group" "eks_workers" {
  name        = "io107-eks-workers"
  description = "IO-107 SDLC Pipeline EKS worker nodes"
  vpc_id      = aws_vpc.training.id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.common_tags, { Name = "io107-eks-workers" })
}


resource "aws_security_group" "training_db" {
  name        = var.db_security_group_name
  description = "IO-107 SDLC Pipeline training Aurora cluster — ingress from EKS workers only"
  vpc_id      = aws_vpc.training.id

  ingress {
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [aws_security_group.eks_workers.id]
    description     = "Postgres from EKS workers"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.common_tags, { Name = var.db_security_group_name })
}

resource "aws_db_subnet_group" "training" {
  name        = var.db_subnet_group_name
  description = "IO-107 SDLC Pipeline training Aurora — private subnets across 3 AZs"
  subnet_ids  = aws_subnet.private[*].id
  tags        = merge(local.common_tags, { Name = var.db_subnet_group_name })
}



# ----- EKS cluster ----------------------------------------------------------

resource "aws_iam_role" "eks_cluster" {
  name = "io107-eks-cluster-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "eks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = local.common_tags
}

resource "aws_iam_role_policy_attachment" "eks_cluster_policy" {
  role       = aws_iam_role.eks_cluster.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
}

resource "aws_eks_cluster" "training" {
  name     = var.eks_cluster_name
  role_arn = aws_iam_role.eks_cluster.arn
  version  = var.eks_kubernetes_version

  vpc_config {
    subnet_ids              = concat(aws_subnet.public[*].id, aws_subnet.private[*].id)
    endpoint_private_access = true
    endpoint_public_access  = true
  }

  enabled_cluster_log_types = ["api", "audit", "authenticator"]

  depends_on = [aws_iam_role_policy_attachment.eks_cluster_policy]

  tags = local.common_tags
}

resource "aws_iam_role" "eks_nodes" {
  name = "io107-eks-nodes-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = local.common_tags
}

resource "aws_iam_role_policy_attachment" "eks_nodes" {
  for_each = toset([
    "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
  ])
  role       = aws_iam_role.eks_nodes.name
  policy_arn = each.value
}

resource "aws_eks_node_group" "training" {
  cluster_name    = aws_eks_cluster.training.name
  node_group_name = "io107-training-nodes"
  node_role_arn   = aws_iam_role.eks_nodes.arn
  subnet_ids      = aws_subnet.private[*].id
  instance_types  = var.eks_node_instance_types

  scaling_config {
    desired_size = var.eks_node_desired_size
    max_size     = var.eks_node_max_size
    min_size     = 1
  }

  depends_on = [aws_iam_role_policy_attachment.eks_nodes]
  tags       = local.common_tags
}

# ----- IRSA OIDC ------------------------------------------------------------

data "tls_certificate" "eks_oidc" {
  url = aws_eks_cluster.training.identity[0].oidc[0].issuer
}

resource "aws_iam_openid_connect_provider" "eks_irsa" {
  url             = aws_eks_cluster.training.identity[0].oidc[0].issuer
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.eks_oidc.certificates[0].sha1_fingerprint]
  tags            = local.common_tags
}


# ----- CodeStar source connection -------------------------------------------

resource "aws_codestarconnections_connection" "source" {
  name          = "io107-source"
  provider_type = var.codestar_provider
  tags          = local.common_tags
}
# NOTE: After `terraform apply`, this connection is in PENDING state. An admin
# must open the AWS Console → CodePipeline → Settings → Connections, select
# the connection, and complete the OAuth flow. One-time, per region.

# ----- Shared CodeBuild service role ----------------------------------------

resource "aws_iam_role" "codebuild_service" {
  name = "io107-codebuild-service-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "codebuild.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = local.common_tags
}

# Broad lab-environment policy — see labforge/python/generate_iam_policy.py for
# the per-course scoped variant if you need to tighten later.
resource "aws_iam_role_policy" "codebuild_service" {
  name = "io107-codebuild-service-inline"
  role = aws_iam_role.codebuild_service.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
          "ecr:GetAuthorizationToken",
          "ecr:BatchCheckLayerAvailability",
          "ecr:GetDownloadUrlForLayer",
          "ecr:BatchGetImage",
          "ecr:PutImage",
          "ecr:InitiateLayerUpload",
          "ecr:UploadLayerPart",
          "ecr:CompleteLayerUpload",
          "eks:DescribeCluster",
          "eks:AccessKubernetesApi",
          "rds:DescribeDBClusters",
          "rds:DescribeDBInstances",
          "rds:ModifyDBCluster",
          "rds:CreateBlueGreenDeployment",
          "rds:DescribeBlueGreenDeployments",
          "rds:SwitchoverBlueGreenDeployment",
          "rds:DeleteBlueGreenDeployment",
          "secretsmanager:GetSecretValue",
          "kms:Decrypt",
          "kms:GenerateDataKey",
          "sts:GetCallerIdentity",
          "s3:GetObject",
          "s3:PutObject",
          "s3:GetBucketLocation",
          "s3:ListBucket"
        ]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = [
          "iam:PassRole"
        ]
        Resource = "*"
        Condition = {
          StringLike = {
            "iam:PassedToService" = ["codebuild.amazonaws.com", "codepipeline.amazonaws.com"]
          }
        }
      }
    ]
  })
}

# ----- Shared CodePipeline service role -------------------------------------

resource "aws_iam_role" "codepipeline_service" {
  name = "io107-codepipeline-service-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "codepipeline.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = local.common_tags
}

resource "aws_iam_role_policy" "codepipeline_service" {
  name = "io107-codepipeline-service-inline"
  role = aws_iam_role.codepipeline_service.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "codebuild:BatchGetBuilds",
          "codebuild:StartBuild",
          "codestar-connections:UseConnection",
          "s3:GetObject",
          "s3:PutObject",
          "s3:GetBucketVersioning",
          "iam:PassRole"
        ]
        Resource = "*"
      }
    ]
  })
}
