###############################################################################
# IO-107 SDLC Pipeline — training_env / outputs.tf
#
# These outputs are consumed by the student_bootstrap/ module via a
# `terraform_remote_state` data source. Keep names stable; renaming breaks
# student bootstrap applies.
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

output "vpc_id" {
  value       = aws_vpc.training.id
  description = "Training VPC ID."
}

output "private_subnet_ids" {
  value       = aws_subnet.private[*].id
  description = "Private subnets (Aurora + EKS workers live here)."
}

output "public_subnet_ids" {
  value       = aws_subnet.public[*].id
  description = "Public subnets (LoadBalancer services land here)."
}

output "eks_workers_security_group_id" {
  value       = aws_security_group.eks_workers.id
  description = "SG attached to EKS workers — student_bootstrap references for Aurora ingress."
}


output "db_security_group_id" {
  value       = aws_security_group.training_db.id
  description = "SG for per-student Aurora clusters."
}

output "db_subnet_group_name" {
  value       = aws_db_subnet_group.training.name
  description = "DB subnet group name — student_bootstrap references this."
}


output "ecr_repo_urls" {
  value       = { for k, r in aws_ecr_repository.app : k => r.repository_url }
  description = "Map of ECR repo name → registry URL."
}

output "kms_rds_key_arn" {
  value       = aws_kms_key.training_rds.arn
  description = "KMS key for Aurora / RDS storage encryption."
}

output "kms_s3_key_arn" {
  value       = aws_kms_key.training_s3.arn
  description = "KMS key for S3 (artifact bucket + lab data)."
}

output "kms_logs_key_arn" {
  value       = aws_kms_key.training_logs.arn
  description = "KMS key for CloudWatch / CloudTrail log encryption."
}


output "eks_cluster_name" {
  value       = aws_eks_cluster.training.name
  description = "EKS cluster name — referenced by every lab's buildspec CLUSTER_NAME var."
}

output "eks_cluster_endpoint" {
  value       = aws_eks_cluster.training.endpoint
  description = "EKS API server endpoint."
}

output "eks_oidc_provider_arn" {
  value       = aws_iam_openid_connect_provider.eks_irsa.arn
  description = "OIDC provider ARN — student_bootstrap uses this for IRSA trust policies."
}

output "eks_oidc_issuer" {
  value       = aws_eks_cluster.training.identity[0].oidc[0].issuer
  description = "OIDC issuer URL — substring used in IRSA trust policy condition keys."
}


output "codestar_connection_arn" {
  value       = aws_codestarconnections_connection.source.arn
  description = "CodeStar source connection ARN — used by every student pipeline's Source stage."
}

output "codebuild_service_role_arn" {
  value       = aws_iam_role.codebuild_service.arn
  description = "Shared CodeBuild execution role used by all student pipelines."
}

output "codepipeline_service_role_arn" {
  value       = aws_iam_role.codepipeline_service.arn
  description = "Shared CodePipeline service role used by all student pipelines."
}
