###############################################################################
# IO-107 SDLC Pipeline — training_env / variables.tf
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

variable "aws_region" {
  description = "AWS region for the training environment. One training_env apply per region."
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr" {
  description = "CIDR block for the training VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "eks_cluster_name" {
  description = "Name of the shared EKS cluster. Referenced by name in each lab's buildspec."
  type        = string
  default     = "training-eks-cluster"
}

variable "eks_kubernetes_version" {
  description = "Kubernetes version for the EKS cluster control plane."
  type        = string
  default     = "1.29"
}

variable "eks_node_instance_types" {
  description = "Instance types for the EKS managed node group."
  type        = list(string)
  default     = ["t3.medium"]
}

variable "eks_node_desired_size" {
  description = "Desired number of EKS worker nodes. Scale based on expected student count."
  type        = number
  default     = 2
}

variable "eks_node_max_size" {
  description = "Maximum EKS worker nodes."
  type        = number
  default     = 6
}

variable "ecr_repo_names" {
  description = "Application image repositories to create in ECR. One per containerised lab app."
  type        = list(string)
  default     = ["myapp", "nginx"]
}

variable "db_subnet_group_name" {
  description = "Name of the DB subnet group used by the training Aurora cluster(s)."
  type        = string
  default     = "training"
}

variable "db_security_group_name" {
  description = "Name of the security group attached to the training Aurora cluster(s). Ingress from the EKS worker SG only."
  type        = string
  default     = "training_db"
}

variable "codestar_provider" {
  description = "Source provider for student pipelines. One of: GitHub, GitHubEnterpriseServer, Bitbucket."
  type        = string
  default     = "GitHub"
}
