###############################################################################
# IO-107 SDLC Pipeline — training_env / versions.tf
#
# Provider versions for the shared training environment. Pinned to known-good
# major versions; the AWS provider 5.x line includes all the resources this
# module needs (EKS 1.29 support, RDS Blue/Green via aws_rds_cluster_instance,
# CodeStar connection).
#
# Backend (S3 + DynamoDB lock table) intentionally not configured here — the
# instructor bootstraps that separately. See instructor_pre_class_setup.md
# in the course root.
#
# Generated by labforge untagged on 2026-05-15.
###############################################################################

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.40"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.27"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      ManagedBy   = "labforge"
      Course      = "IO-107 SDLC Pipeline"
      Environment = "training"
      Module      = "training_env"
    }
  }
}
